### ISSUE TITLE
CONTRIBUTING.md

### ISSUE THREAD

**Issue by orchid00** [swcarpentry/shell-novice-es#3] opened 2018-02-23 19:15 UTC
Por favor Francisco, checka los links @map0logo

**Comment by orchid00** [comment] 2018-02-26 19:16
Hola @map0logo puedes revisar el contributing
siguiendo los lineamientos https://github.com/Carpentries-ES/board/blob/master/Convenciones_Traduccion.md
Due date: 2018-03-05

https://github.com/swcarpentry/shell-novice-es/tree/gh-pages/_episodes

**Comment by ErinBecker** [comment] 2018-03-09 22:32
This is a duplicate of https://github.com/swcarpentry/shell-novice-es/issues/14. Closing.

**Closed as completed by ErinBecker** 2018-03-09 22:32 UTC
